[build]
  base = "docs"
  command = "npm run build"
  publish = "out"
  # Don't use any build plugins - pure static hosting
  functions = "netlify/functions"

# Headers for static assets
[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirect root to docs (302 temporary)
[[redirects]]
  from = "/"
  to = "/docs"
  status = 302
